version: '3.1'

services:

  db:
    container_name: db-mysql
    image: mysql:8.3
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: wordpress
    volumes:
      - db-test:/var/lib/mysql
    networks:
      app:

  wordpress:
    container_name: php-fpm
    image: wordpress:6.4.3-php8.3-fpm-alpine
    working_dir: /var/www/html/wordpress
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 9000:9000
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      app:

  proxy_server:
    container_name: proxy-nginx
    image: nginx:1.25.3-alpine
    depends_on:
      - wordpress
    restart: always
    volumes:
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf 
      - ./nginx-conf/ssl/ssl.key:/etc/ssl/private/ssl.key
      - ./nginx-conf/ssl/ssl.crt:/etc/ssl/certs/ssl.crt
      - ./nginx-conf/site/index.html:/var/www/site/index.html
      - wp:/var/www/html/wordpress
    ports:
      - 80:80
      - 443:443
    networks:
      app:

volumes:
  wp:
  db-test:

networks:
  app:
    driver: bridge
